= Group 1 - Data mobilization training and guidance on sequence-derived data mobilization

== Faciliators 
Laura Anne Russell and  Dmitry Schigel, GBIF Secretariat

NOTE: Please view the presentations ahead of the live panel session use the https://discourse.gbif.org/t/gnm-2021-global-nodes-meeting-2021/2879[GBIF community forum] to ask questions.

== References

* How to teach the GBIF Data Mobilization course  on site and online
  * https://docs.gbif.org/course-data-mobilization[Data mobilization course^]

* Guide and training materials to support sequence-derived data in GBIF
  * https://docs.gbif-uat.org/course-dna-barcoding[Draft DNA barcoding course^]
  * https://docs.gbif-uat.org/publishing-dna-derived-data/1.0/en/[Draft guide on Publishing DNA-derived data through biodiversity data platforms^]

== Presentations

*Update on BioDATA  - DNA metabarcoding data management*

Presentation by Dag Terje Filip Endresen, GBIF Node Manager

video::566509989[vimeo]

== Live demo

Group 1 - Data mobilization training and guidance on sequence-derived data mobilization

Facilitation by Laura Anne Russell and  Dmitry Schigel, GBIF Secretariat

video::568827627[vimeo]

