= Theme 1 - The role of nodes in GBIF’s next strategic period 

== Panel moderator

Mélianie Raymond, GBIF Secretariat

== Goal

To explore key themes with panels of experts from the community, building on presentations from the nodes and Secretariat on topics that were requested in the consultation with nodes.

NOTE: Please view the presentations ahead of the live panel discussion and use the https://discourse.gbif.org/t/gnm-2021-global-nodes-meeting-2021/2879[GBIF community forum^] to ask questions.

== Presentations

*16th Global Nodes Meeting 2021 Welcome*

Presentation by Nodes Committee Chair, André Heughebaert

video::566492345[vimeo]

*The Role of the Nodes in Next GBIF Strategic Plan*

Presentation by Executive Secretary, Joe Miller, GBIF Secretariat

video::565570188[vimeo]

*GBIF’s Values*

Presentation by Tim Hirsch, Deputy Director, GBIF Secretariat

video::568321140[vimeo]

*GBIF Resource Mobilization Strategy*

Presentation by Hilary Goodson, Strategic Partnership Officer, GBIF Secretariat

Please review this background document as references for the live demo session **[background document](/assets/rms.pdf)

video::566017188[vimeo]

*Strengthening regional capacity in GBIF*

Presentation by Mélianie Raymond and Maheva Bagard Laursen, Participation and Engagement, GBIF Secretariat

video::566458271[vimeo]

== Panel discussion

*The role of nodes in GBIF’s next strategic period*

Theme 1 Live panel with all presenters. Panel moderator: Mélianie Raymond, Participation and Engagement, GBIF Secretariat

video::568778490[vimeo]
