= Speed dating networking activity

== Facilitator

Maheva Bagaard Laursen, GBIF Secretariat

== Goal 

For nodes to share ideas for collaborative projects with other nodes in the network.

== Format

We will use breakout rooms in Zoom and engage conversation with each other around the questions below: 

* What type of support do you receive for your node activities?

* What are the main areas of success in resourcing your node’s activities / How did you successfully argue the case for GBIF participation?

* What tips and recommendations on resourcing (funding sources, institutional support, support from the local/national/regional network, support from GBIF community, in kind support, etc.) and key areas of success can you share?

* In your experience, what are the most efficient tools to demonstrate the importance of GBIF nodes and the importance of formal GBIF participation / What would be the tools you wish you had to  demonstrate the importance of GBIF nodes and the importance of formal GBIF participation?

NOTE:  link:/assets/Speed dating activity _ GNM 2021.pptx.pdf[Slides from the session]
