= Supporting national biodiversity commitments and the science-policy interface

== Context

Through partnerships and coordination, nodes can enable data flows into indicators and reporting processes relating to biodiversity status and trends, supporting commitments under the Convention on Biological Diversity (CBD) and the Sustainable Development Goals. By building linkages with the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES), nodes can support biodiversity assessments by providing access to biodiversity data and enabling policy-related research based on GBIF-mediated data. These linkages can also support the nodes in terms of raising awareness of the value of open biodiversity data to national policy and commitments, as well as identifying policy-relevant gaps in data availability. (See https://docs.gbif.org/nodes-implementation-2023/en/#2-support-national-biodiversity-commitments-and-the-science-policy-interface[Nodes Strategy #2] for more detail.)

== Learning objectives

== Trainers

https://orcid.org/0009-0009-8717-8904[Michelle Judge^], Node Manager, Ireland

https://orcid.org/0000-0003-2409-2408[Melisa Ojeda^], Node Manager, Guatemala

Secretariat consultants: https://orcid.org/0000-0002-5015-5807[Tim Hirsch^], Deputy Director, and https://orcid.org/0000-0002-5468-2452[Andrew Rodrigues^], Data Partnerships Officer

== Preparation

=== Convention on Biological Diversity (CBD)

*Watch introduction video* on the Post-2020 Global Biodiversity Framework (YouTube - 1:14 min)

video::H0Bp5jo4xic[youtube]

&nbsp;

*Watch video* on the Post-2020 Global Biodiversity Framework and Targets (YouTube - 8:35 min; https://www.youtube.com/watch?v=e48M-DupuYo[Spanish^])

video::hnufsBNtFbw[youtube]

&nbsp;

*Read* https://www.cbd.int/doc/publications/cbd-sustain-en.pdf[Sustaining life on Earth^] (PDF 500 KB)

*Investigate* the https://www.cbd.int/countries/[CBD in your country^] (Download xref:attachment$CBD-in-your-country.docx[worksheet])

. Does your country have a current National Biodiversity Strategy and Action Plan (NBSAP)? 
. Is your country updating its NBSAP? 
. If so, what is the state of the process? Who is coordinating it? 
. Are you engaged in the process - if so, how? If not, how could you be involved? 

=== Global Biodiversity Framework Kunming-Montreal

*Read* the https://www.cbd.int/gbf/[overview^]* (webpage)

== Module 1

=== Introduction to CBD

&nbsp;

=== GBIF and CBD

&nbsp;

=== Node engagement with CBD - Ireland

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRRJMh7Ln7wTKknX5R_HczZdEupKwYLc7E0XtImVTRFifjpWvzfFpROYxCiOA3uHw/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTpyse82vHEpjxQQr9ulU1PwSP1iqmP6GZQL7_DUrxV8irVsqyrpCAJJ_ql85Phbw/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== National examples

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSlbmGR9veXr7-UQvGuMSf7CEcGBpYMvF7ZQyGUM31zWcA4YmexbL_rXuBf6dAQnQ/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Module 2

&nbsp;

=== Supporting national reporting requirements

&nbsp;

== Action plan

&nbsp;


