= Supporting national biodiversity commitments and the science-policy interface

== Context

Through partnerships and coordination, nodes can enable data flows into indicators and reporting processes relating to biodiversity status and trends, supporting commitments under the Convention on Biological Diversity (CBD) and the Sustainable Development Goals. By building linkages with the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES), nodes can support biodiversity assessments by providing access to biodiversity data and enabling policy-related research based on GBIF-mediated data. These linkages can also support the nodes in terms of raising awareness of the value of open biodiversity data to national policy and commitments, as well as identifying policy-relevant gaps in data availability. (See https://docs.gbif.org/nodes-implementation-2023/en/#2-support-national-biodiversity-commitments-and-the-science-policy-interface[Nodes Strategy #2] for more detail.)

// == Learning objectives

== Trainers

Michelle Judge, Node Manager, Ireland

Melisa Ojeda, Node Manager, Guatemala

Secretariat consultants: Tim Hirsch and Andrew Rodrigues

== Preparation

. Learn about the Convention on Biological Diversity (CBD)
.. Watch introduction video on the Post-2020 Global Biodiversity Framework (YouTube - 1:14 min)
video::H0Bp5jo4xic[youtube]
.. Watch video on the Post-2020 Global Biodiversity Framework and Targets (YouTube - 8:35 min; https://www.youtube.com/watch?v=e48M-DupuYo[Spanish^])
video::hnufsBNtFbw[youtube]
.. Read https://www.cbd.int/doc/publications/cbd-sustain-en.pdf[Sustaining life on Earth^] (PDF 500 KB)
.. Investigate the https://www.cbd.int/countries/[CBD in your country^] (download worksheet)
... Does your country have a current National Biodiversity Strategy and Action Plan (NBSAP)? 
... Is your country updating its NBSAP? 
... If so, what is the state of the process? Who is coordinating it? 
... Are you engaged in the process - if so, how? If not, how could you be involved? 

. Learn about the Global Biodiversity Framework Kunming-Montreal
.. Read the https://www.cbd.int/gbf/[Overview^] (webpage)
