= Promoting open biodiversity data approaches within the business sector

== Context

In recent years, several nodes have scaled up engagement with the private sector resulting in increased data mobilization, partnerships, and communication materials to support further engagement (see the resources developed and available for reuse through the https://www.gbif.org/project/2Zik1tfJoh3C92ZslvhDIr/[CESP OpenPSD project^] and the https://www.gbif.org/business[GBIF business sector page^]). (See https://docs.gbif.org/nodes-implementation-2023/en/#3-promote-open-biodiversity-data-approaches-within-the-business-and-finance-sectors[Nodes Strategy #3^] for more detail.)

== Learning objectives

== Trainers

https://orcid.org/0000-0001-6902-1465[Anne-Sophie Archambeau^], Node Manager, France

https://orcid.org/0000-0003-1070-1081[Ricardo Ortiz^], Node Manager, Colombia

Secretariat consultant: https://orcid.org/0000-0002-5468-2452[Andrew Rodrigues^], Data Partnerships Officer

== Preparation

*Read* about https://www.gbif.org/business[GBIF and Business^] (webpage)

*Watch video* on https://vimeo.com/473377963[Open Private Sector Data^] (PSD) (Vimeo - 4:43 min)

video::473377963[vimeo]

*Read* about https://www.gbif.org/data4nature[Data4Nature^]* (webpage and associated Vimeo - 1:17 min)

*Read* about the https://www.gbif.org/news/6wybKvTFVZPWTLioIcOuB3/the-equator-principles-encourage-open-access-to-environmental-impact-data-through-the-gbif-network[Equator Principles^] (webpage)

*Read* https://docs.gbif.org/private-sector-data-publishing/2.0/en/[Guidance for private companies to become data publishers through GBIF^] (guide)

== Module 1

&nbsp;

=== GBIF and the business sector

&nbsp;

video::869504416[vimeo]

&nbsp;

=== Business sector - France

&nbsp;
            
=== Business sector - Colombia

&nbsp;

=== Nodes experience

&nbsp;

== Module 2

&nbsp;

=== Engaging stakeholders

&nbsp;

=== Key aspects for engaging the business sector

&nbsp;

== Action plan
