= Engaging research communities for data mobilization and use

== Context

Nodes play an essential role in building engagement with researchers within their countries and networks, promoting open science principles (in line with the https://en.unesco.org/science-sustainable-future/open-science/recommendation[UNESCO open science recommendation^]) and building communities of data publishers and users. Research communities can help to identify data gaps, data needs, and challenges in the use of the available data that can help nodes to prioritize activities. Several nodes have succeeded in embedding GBIF within academic training programmes (see https://www.gbif.org/article/aA0MjVddRiRFOX2SEs7mT/[guiding example from Benin^]), developing capacity and encouraging new generations of researchers to follow open science practices. GBIF’s focus on thematic communities (including soil, freshwater and disease vector thematic communities in 2023), will lead to growing interest in data publishing and data use from researchers that will seek to connect with nodes for support. (See https://docs.gbif.org/nodes-implementation-2023/en/#1-engage-research-communities-for-data-mobilization-and-use[Nodes Strategy #1] for more detail.

== Learning objectives

* 
* 

== Trainers

https://orcid.org/0000-0002-0846-9116[Dimitri Brosens^], Node Manager, Belgium

https://orcid.org/0000-0003-4212-6448[Dr. Jean C. Ganglo^], Node Manager, Benin

Secretariat consultant: https://orcid.org/0000-0002-2919-1168[Dmitry Schigel^], Scientific Officer

== Preparation

*Read* about https://www.gbif.org/data-use[how and where GBIF-mediated data is used^].

== Module 1

=== GBIF as a research infrastructure

* MoU
* Strategic freamwork
* Work programme
* Nodes best practice guide
* Networking professionally and nationally

=== Engaging research communities

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSnbjTSgJF26dvY3FZq7JO464bYz4JsmDQzYxuJRQXm1Q7RdupGoEJecayvGSaKcw/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Identifying use of science

&nbsp;

== Module 2

&nbsp;

=== Raising the visibility of GBIF and Nodes

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSPilOVE9n-Q_4NyI5kxOhlQLwzmZ6Eo-QqrDZO8JpRCyQY6NgPAtl_GiB0lFrYnTI5wBnSA3-kgtGG/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== National examples

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSDoRXeRoaH6GI9beD7x4lpXzyaY-HrmkDqlma3XWvkraZz8UxRZ83W0ghcVWNBFA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Community engagment BINGO

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRt_6sV0vC17wd6swRehx4V8WtbxRdceOzTNtKlvPG00tL3SejNrRgNzLSR1VV0HyM22jovPT7Bb7A8/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Action plan



