= Engaging research communities for data mobilization and use

== Context

Nodes play an essential role in building engagement with researchers within their countries and networks, promoting open science principles (in line with the https://en.unesco.org/science-sustainable-future/open-science/recommendation[UNESCO open science recommendation^]) and building communities of data publishers and users. Research communities can help to identify data gaps, data needs, and challenges in the use of the available data that can help nodes to prioritize activities. Several nodes have succeeded in embedding GBIF within academic training programmes (see https://www.gbif.org/article/aA0MjVddRiRFOX2SEs7mT/[guiding example from Benin^]), developing capacity and encouraging new generations of researchers to follow open science practices. GBIF’s focus on thematic communities (including soil, freshwater and disease vector thematic communities in 2023), will lead to growing interest in data publishing and data use from researchers that will seek to connect with nodes for support. (See https://docs.gbif.org/nodes-implementation-2023/en/#1-engage-research-communities-for-data-mobilization-and-use[Nodes Strategy #1] for more detail.

// == Learning objectives

== Trainers

Dimitri Brosens, Node Manager, Belgium

Jean Ganglo, Node Manager, Benin

Secretariat consultant: Dmitry Schigel

== Preparation

*Read* about https://www.gbif.org/data-use[how and where GBIF-mediated data is used^].
