= Marine data mobilization session

== Faciliators

Ward Appeltans, OBIS, and Abby Benson, OBIS USA and US GBIF Node

== Goal

To update the community on the collaboration between GBIF and OBIS and discuss how we can work together on marine data mobilization

NOTE: Please view the presentations ahead of the live panel discussion and use the https://discourse.gbif.org/t/gnm-2021-global-nodes-meeting-2021/2879[GBIF community forum^] to ask questions.

== Presentations

*OBIS-GBIF introduction*

Presentation by Ward Appeltans, Project Manager at OBIS

video::566605276[vimeo]

*Welcome statement from Martha Vides*

Presentation by Martha Vides, OBIS

video::566610206[vimeo]

*OBIS and GBIF commonalities and differences*

Presentation by Abby Benson, OBIS USA

video::566605186[vimeo]

*Interoperable and reusable research data in OBIS*

Presentation by Pieter Provoost, UNESCO/IOC Project Office for IODE, OBIS Data Manager

video::566604359[vimeo]

*Collaboration between OBIS and GBIF nodes*

Presentation by Anton Van de Putte, Antarctic Biodiversity Information Facility (ANTABIF)

video::566604232[vimeo]

*Norwegian GBIF marine datasets from OBIS*

Presentation by Rukaya Johaadien, Norwegian GBIF Node Staff

video::566605968[vimeo]

== Live session

OBIS Marine data mobilization

Facilitatation by Ward Appeltans, OBIS, and Abby Benson, OBIS USA and US GBIF Node.

video::570247972[vimeo]
