= Theme 2 - Exploring future directions for GBIF - live panel with all presenters

== Panel moderator

Mélianie Raymond, GBIF Secretariat

== Goal

To explore key themes with panels of experts from the community, building on presentations from the nodes and Secretariat on topics that were requested in the consultation with nodes.

NOTE: Please view the presentations ahead of the live panel discussion and use the https://discourse.gbif.org/t/gnm-2021-global-nodes-meeting-2021/2879[GBIF community forum] to ask questions.

== Presentations

*Aligning GBIF and ALA*

Presentation by Dave Martin and Javier Molina

video::566499732[vimeo]

*Looking ahead: GBIF data model*

Presentation by Tim Robertson, Head of Informatics, GBIF Secretariat

video::564600741[vimeo]

*GBIF and the Post-2020 Global Biodiversity*

Presentation by Andrew Rodrigues, Programme Officer, GBIF Secretariat

video::564608734[vimeo]

*Private-sector engagement: guidance materials, and role of nodes*

Presentation by Andrew Rodrigues, Programme Officer, GBIF Secretariat

video::564604996[vimeo]

*GBIF: potential for a thematic approach*

Presentation by Dmitry Schigel, GBIF Secretariat

video::566502314[vimeo]

*Ambassadors and users*

Presentation by Daniel Noesgaard and Dmitry Schigel, GBIF Secretariat

video::566502365[vimeo]

== Panel discussion

*Exploring future directions for GBIF*

Panel moderator: Mélianie Raymond, GBIF Secretariat

video::569102996[vimeo]
