= Sharing experience

We would like to invite all Node Managers, independently of whether you are able to participate in the training (GNT) or meeting (GNM), to consider submitting slides on the specific topics below.

*Deadline*: 13 September

____
https://gbif.app.box.com/f/360afd35002a42bcbe18bc514f3272ee[Submit slides] by uploading them via Box.
____

== GNT Template

____
xref:attachment$Node-inputs-GNT-template.pptx[Training topics template] (PowerPoint, 20.9 MB)
____

Please use the template to prepare slides on either or both of the following topics. We will select some slides to be presented during the lightning segments, which are brief (3-5 minutes) parts of the training sessions on these two topics. Additionally, the slides you submit will be carefully reviewed for inclusion in the curriculum that we are developing on these topics for reuse in future.

. *Your experiences in supporting national biodiversity commitments and the science-policy interface*. Share details on how your node is currently supporting your country for any of the following:
* National Biodiversity Strategies and Action Plans (NBSAPs) 
* National reports to the CBD and/or other biodiversity-related conventions
* National or subnational legislation and/or regulations relating to biodiversity	
* Technical instruments, documents, or analysis for policy makers
. *Your experiences engaging research communities for data mobilization and use*. Share details on how you are engaging with the research community in your country. Consider how you raise the visibility of GBIF and your node within this community.

== GNM Template

____
xref:attachment$Node-inputs-GNM-template.pptx[Meeting topics template] (PowerPoint, 24.1 MB)
____

Please use the template to prepare slides of any or all of the following topics.  We will share all of the submitted slides for background ahead of the Global Nodes events. Alternatively, you have the option to submit a video presentation, which should ideally be within the range of 3 to 5 minutes.

. *Your experiences with the work underway to expand GBIF’s data model*. Share details on how you are engaging with this work, and your perspective on what the new data model will mean for your node in future.
. *Your experiences with GBIF’s capacity development programmes, such as BID and CESP*. Share details from your involvement in projects supported by these programmes, and your views on how these programmes can best support the work of nodes going forward.
. *Your experiences of working with the GBIF regional support teams*. Share any interactions you have had with the regional support teams in Asia, and through the BID programme, as well as your ideas for how the regional support teams and nodes can best work together to strengthen and expand GBIF’s community of practice.
