= Supporting Nodes through GBIF Capacity Development Programmes

== Context

GBIF runs capacity development programmes that focus on building capacity for biodiversity data mobilization and use, cooperation and knowledge sharing. This session of the Global Nodes Meeting will be an opportunity to discuss how nodes currently participate in and support these programmes, and ideas for how the programmes can be of even greater benefit to the nodes and broader community in future.

The programmes we will be focusing on in the discussion are the Capacity Enhancement Support Programme (CESP) and the Biodiversity Information for Development (BID) programme. We will also discuss work underway to develop an onboarding programme to help new nodes to get started in the GBIF community.

https://www.gbif.org/programme/82219/capacity-enhancement-support-programme[CESP^] has since 2014 provided small grants to support capacity development projects co-funded by the nodes. The annual calls for proposals under this programme provide co-funding to GBIF Participants for capacity enhancement projects based on combinations of mentoring activities, regional events, training workshops and the production and adaptation of documentation and materials.
 
Launched in 2015, the https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development[BID programme] aims to improve the availability and accessibility of biodiversity data in developing countries to enable the effective implementation of national and multilateral agreements such as the Kunming-Montreal Global Biodiversity Framework. With funding coming mostly from the European Union, the BID programme has supported over 100 projects in sub-Saharan Africa, the Caribbean and the Pacific to date. We are currently preparing for a continuation of the BID programme, which we hope to launch in 2024.

== Preparation

In preparation for this session, we invite you to:

. Attend the https://www.gbif.org/event/DL7vdW3Q9spyscdi5kaj6/biodiversity-information-for-development-showcase[BID Showcase event] on 25 September 2023 to learn more about the impact of the programme to date and to participate in discussions on its future. The event will be recorded if you are unable to attend live.
. Review the https://www.gbif.org/composition/4R5Ot70guupksCkTNbq1oe/cesp-all-projects[CESP project pages] to see the types of activities that have been funded and get inspired by their results.
. Read through slides provided by nodes in preparation for this session and consider xref:sharingexperience.adoc[sharing slides] on your node’s experience with GBIF capacity development programmes.

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTqNwemQzemqCd1x-ckOzs1JPkTGj9sJwI_nHw0blyTkgvG85SPnKJOEBuBRSJM8Q/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
