= Developing Capacity within Regional Communities of Practice

== Context

Since 2008, GBIF has supported six regional networks around the world to encourage and strengthen regional collaboration and information exchange among Participants. 
These regional sub-committees are explained in the https://assets.ctfassets.net/uo17ejk9rkwj/73Shop9ogovEILrXFGLW6R/933d0e904fce33c762bd0d3b0480f7a1/Terms_of_Reference_for_the_Nodes_Committee_-_September_2017.pdf[Terms of Reference for the Nodes Committee^], and on the https://www.gbif.org/nodes[GBIF nodes page^].

A key theme across the regional sub-committees is the coordination of outreach actions to encourage broader engagement in GBIF at all levels, particularly as formal Participants in the network. 
The GBIF Governing Board commissioned an https://www.gbif.org/news/5WZThcL928vmPnSvrGhZfE/report-reveals-return-on-investments-in-gbif[economic valuation of the GBIF network^] to demonstrate the return on investments in GBIF. 
The study by Deloitte Access Economics published this year supports Participants in outlining GBIF’s value proposition and the benefits of being in the network. 
We hope that regions can reflect on how this study can help to support outreach efforts. 

During the Global Nodes Meeting, the elected regional representatives will organize regional breakout sessions, to discuss strengthening regional engagement and plans for regional nodes meetings in 2024.

== Preparation

In preparation for the regional breakout sessions, we invite you to:

. https://www.gbif.org/contact-us/directory?group=nsg[Contact your regional representative and deputy^] if you have items you wish to add to the agenda for the regional breakout session.
. Watch a video from Kyle Copas, GBIF Communications Manager, on estimating the national value of time savings from GBIF-enabled research and consider how you can use this to support your node and outreach efforts in your region.
