= Cross-regional knowledge exchange

== Context

[NOTE.description]
====
The GBIF network of nodes spans more than sixty countries and areas, as well as over forty organizations with a regional scope worldwide. Recognizing the importance of local, national, and regional contexts in shaping their work, nodes have developed a wide range of tools and mechanisms to help fulfill their mission.

In this session, nodes will work in small groups to reflect on shared interests and cross-regional challenges. It will also provide an opportunity to exchange knowledge and best practices, and to explore ways of developing or strengthening collaboration across regions in support of joint priorities.

By the end of the session, participants will have a clearer understanding of current priorities and available expertise across the network, along with concrete ideas for potential new collaborations and opportunities for knowledge sharing.
====

== Objectives

[NOTE.objectives]
====
* To learn from and be inspired by node-led initiatives and best practices across the GBIF network
* To discuss and identify cross-regional topics, priorities and/or challenges
* To discuss and identify cross-regional opportunities for new collaborations or partnerships
====

== Preparation

[NOTE.prep]
====
In preparation, we invite you to:

. Reflect on your node’s current workflows and engagement strategies.
. Identify one success story to share with fellow nodes (e.g., a successful engagement initiative, an efficiency gain in your node’s activities, a successful partnership or an effort that improved your node’s visibility).
. List one challenge for which you would like to explore possible solutions.
====

//&nbsp;

//++++
//<div style='padding:56.25% 0 0 0;position:relative;'><iframe src='https://vimeo.com/showcase/10660172/embed' allowfullscreen frameborder='0' style='position:absolute;top:0;left:0;width:100%;height:100%;'></iframe></div>
//++++

//&nbsp;

//++++
//<div class="responsive-slides">
//  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTx0vOBakwFc5dd2VdGcefovz4ycQZdRc2VjQ9uBeQKhAM_cer6iN4Fr4t6ZudrHA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
//</div>
//++++

//== Meeting

//[NOTE.presentation]
//====
//text here.
//====

//&nbsp;

//++++
//<div class="responsive-slides">
//  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQ8IO6VipL95Y4lbU39H7eekkNNfYEgpVa8DjS1PyZpP8xoMKFIF-WN0PYPjVQXIA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
//</div>
//++++

//&nbsp;

//[NOTE.presentation]
//====
//Text here.
//====

//&nbsp;

//++++
//<div class="responsive-slides">
//  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTx4tcWGs6dR-0lUPi6jyeGMsHJbvQko_3yJu_PA2mr45SmN2Bsp0d6yYObCdHf-g/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
//</div>
//++++

//&nbsp;

//[NOTE.presentation]
//====
//text here.
//====

//&nbsp;

//++++
//<div class="responsive-slides">
//  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSECC6gMvq5LOKiGcOkwem_anK1ly_pGTR141FFsC4ejAjZGgSNPFjgqw1CYRy0Kg/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
//</div>
//++++

//&nbsp;
