= Regional communities of practice

== Context

[NOTE.description]
====
Since 2008, GBIF has supported six regional networks around the world to encourage and strengthen regional collaboration and information exchange among Participants. These regional sub-committees are explained in the https://assets.ctfassets.net/uo17ejk9rkwj/73Shop9ogovEILrXFGLW6R/933d0e904fce33c762bd0d3b0480f7a1/Terms_of_Reference_for_the_Nodes_Committee_-_September_2017.pdf[Terms of Reference for the Nodes Committee^], and on the https://www.gbif.org/nodes[GBIF nodes page^].

A key theme across the regional sub-committees is the coordination of outreach actions to encourage broader engagement in GBIF at all levels, particularly as formal Participants in the network. 

During the Global Nodes Meeting, the elected regional representatives will organize regional breakout sessions, to discuss strengthening regional engagement and plans for regional nodes meetings in 2026.
====

== Objectives

[NOTE.objectives]
====
* To enable regional discussions to build plans for regional meetings in 2026
* To review current mechanisms for regional engagement and explore opportunities for improvement
* To increase understanding of the scope of the work of the regional support teams and explore how it can better complement the efforts of the nodes and regional representatives
* To identify and discuss current and upcoming opportunities for regional collaboration
====

== Preparation

[NOTE.prep]
====
In preparation for the regional breakout sessions, we invite you to:

. Review the https://docs.gbif.org/nodes-implementation-2025/en/[GBIF Nodes Implementation Plan 2025^] and reflect on your node’s strengths and areas for growth.
. Consider potential opportunities to strengthen regional collaboration and enhance the impact of the regional support teams’ work.
. https://www.gbif.org/contact-us/directory?group=nsg[Contact your regional representative and deputy^] if you have items you wish to add to the agenda for the regional breakout session.
====

== Regional breakout sessions

[NOTE.activity]
====
In this session, nodes will meet in regional groupings to share updates, reflect on progress, and discuss priorities for the future.

*Instructions*

[NOTE]
Room locations and Zoom links are provided below. If you have difficulties with any of the links, further details are provided in https://gbif.box.com/s/3gb69g9px930095r3j3du03oxk6fnnx4[this document^].

*Plenary room, Auditorium 2*

_Europe & Central Asia_
Zoom: https://zoom.us/j/9904812267?pwd=gdcJAmXGy9zcxzZabKYRSAX85BSc4q.1&omn=91568744289

_North America_
Zoom: https://us02web.zoom.us/j/87599193146

*Breakout room,  Room H404*

_Latin America & Caribbean_
Zoom: https://zoom.us/j/91538415542?pwd=CEr7ihbrmwIxDmCF4XTCkA7S2suGvj.1 

_Oceania_

*Breakout room, Room  H304*

_Africa_ 
Zoom: https://zoom.us/j/93293795056?pwd=wGKA2aJSguiUOfq1qJbxTz35qYXMEF.1

_Asia_

Discussions will be led by the regional representatives and will cover two themes:

* Progress and challenges on the seven objectives of the Nodes Implementation Plan 2025.
* Planning for the 2026 Regional Nodes Meeting, including hosts, dates, agenda, and engagement opportunities.

At the end of the session, regional representatives should https://docs.google.com/document/d/1kYXi30YAuPAo8EGaEmmyNZafh-HgN6PLQlQzdEE5gkc/edit?usp=sharing[*submit up to two highlights*^] to the chair of the NSG to be reflected in the closing wrap-up.
====

== Plenary meeting wrap-up

[NOTE.presentation]
====
Anne-Sophie Archambeau, Chair of the Nodes Committee, will wrap up the meeting with her reflections on the discussions of the day.
====
