= Regional communities of practice

== Context

[NOTE.description]
====
Since 2008, GBIF has supported six regional networks around the world to encourage and strengthen regional collaboration and information exchange among Participants. These regional sub-committees are explained in the https://assets.ctfassets.net/uo17ejk9rkwj/73Shop9ogovEILrXFGLW6R/933d0e904fce33c762bd0d3b0480f7a1/Terms_of_Reference_for_the_Nodes_Committee_-_September_2017.pdf[Terms of Reference for the Nodes Committee^], and on the https://www.gbif.org/nodes[GBIF nodes page^].

A key theme across the regional sub-committees is the coordination of outreach actions to encourage broader engagement in GBIF at all levels, particularly as formal Participants in the network. 

During the Global Nodes Meeting, the elected regional representatives will organize regional breakout sessions, to discuss strengthening regional engagement and plans for regional nodes meetings in 2026.
====

== Objectives

[NOTE.objectives]
====
* To enable regional discussions to build plans for regional meetings in 2026
* To review current mechanisms for regional engagement and explore opportunities for improvement
* To increase understanding of the scope of the work of the regional support teams and explore how it can better complement the efforts of the nodes and regional representatives
* To identify and discuss current and upcoming opportunities for regional collaboration
====

== Preparation

[NOTE.prep]
====
In preparation for the regional breakout sessions, we invite you to:

. Review the https://docs.gbif.org/nodes-implementation-2025/en/[GBIF Nodes Implementation Plan 2025^] and reflect on your node’s strengths and areas for growth
. Consider potential opportunities to strengthen regional collaboration and enhance the impact of the regional support teams’ work
. https://www.gbif.org/contact-us/directory?group=nsg[Contact your regional representative and deputy^] if you have items you wish to add to the agenda for the regional breakout session
====


