= Sharing experience

We would like to invite all Node Managers, independently of whether you are able to participate in the training (GNT) or meeting (GNM), to consider submitting slides on the specific topics below.

____
https://gbif.app.box.com/f/360afd35002a42bcbe18bc514f3272ee[Submit slides] by uploading them via Box.
____

== GNM Template

____
xref:attachment$Node-inputs-GNM-template.pptx[Meeting topics template] (PowerPoint, 24.1 MB)
____

Please use the template to prepare slides to share your experience ahead of the Global Nodes Meeting. We will share all of the submitted slides for background ahead of the events. Alternatively, you have the option to submit a video presentation, which should ideally be within the range of 3 to 5 minutes.

We are specifically requesting experience sharing relating to engagement through thematic areas of relevance, including, but not limited to:

* Agrobiodiversity
* Invasives
* Indigenous data governance
* Marine biodiversity data

We are also looking for examples of regional or cross-regional collaborations, particularly any that have led to long-term partnerships or the engagement of new GBIF Participants.
