= Buddy activities

We invite all buddy groups to get to know one another and build connections. Whenever possible, buddy groups will be kept together during activities at the Global Nodes Training and Meeting. This will also provide opportunities to complete as many of the _Buddy Challenges_ as possible during the Global Nodes Events.

These challenges are designed to encourage interaction and collaboration while complementing the Global Nodes Event’s full program.

== Before the event

. Find your buddies
. We encourage introducing yourself to your buddies in advance, for example by email/WhatsApp/other preferred channel. You may wish to share:

* Your country or organization
* Your role within the GBIF community (e.g., Node staff, Node manager, Head of Delegation Observer, Mentor, Trainer, Reviewer, Open Data Ambassador, Translator, etc.)
* How long you have been part of the GBIF community
* Which events you will attend in Colombia (e.g., Global Nodes Training, Global Nodes Meeting, Icebreaker, GBIF Governing Board, Living Data Conference)
* One goal you hope to achieve or one thing you hope to learn by attending the Global Nodes Training and Meeting

== During the event

. Discuss your buddies’ interests and introduce them to at least one of your contacts within your region and one outside of your region
. Complete as many of the _Buddy Challenges_ as possible, which will be shared during the event

++++
<iframe src="https://globalnodes.gbif-test.org/en/buddies/_images/buddy-challenges.pdf" frameborder="0" allowfullscreen="true" height="1100" width="100%" align="center"></iframe>
++++

== After the event

. Stay in touch with your buddies and share information that may be of interest to them
. Provide feedback on the buddy system for future improvements